name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Maven Settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>speedcubing-public-projects-release</id>
              <username>${{ secrets.NEXUS_USERNAME }}</username>
              <password>${{ secrets.NEXUS_PASSWORD }}</password>
            </server>
            <server>
              <id>speedcubing-public-projects-snapshot</id>
              <username>${{ secrets.NEXUS_USERNAME }}</username>
              <password>${{ secrets.NEXUS_PASSWORD }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Deploy to Nexus 1
      run: |
        mvn deploy:deploy-file \
          -DgroupId=net.md-5 \
          -DartifactId=bungeecord-config \
          -Dversion=1.8-SNAPSHOT \
          -Dpackaging=jar \
          -Dfile=target/bungeecord-config-1.8-20160221.214615-126.jar \
          -DrepositoryId=speedcubing-public-projects-snapshot \
          -Durl=https://repo.speedcubing.top/repository/maven-public-test/

    - name: Deploy to Nexus 2
      run: |
        mvn deploy:deploy-file \
          -DgroupId=net.md-5 \
          -DartifactId=bungeecord-event \
          -Dversion=1.8-SNAPSHOT \
          -Dpackaging=jar \
          -Dfile=target/bungeecord-event-1.8-20160221.214626-126.jar \
          -DrepositoryId=speedcubing-public-projects-snapshot \
          -Durl=https://repo.speedcubing.top/repository/maven-public-test/

    - name: Deploy to Nexus 3
      run: |
        mvn deploy:deploy-file \
          -DgroupId=net.md-5 \
          -DartifactId=bungeecord-protocol \
          -Dversion=1.8-SNAPSHOT \
          -Dpackaging=jar \
          -Dfile=target/bungeecord-protocol-1.8-20160221.214639-126.jar \
          -DrepositoryId=speedcubing-public-projects-snapshot \
          -Durl=https://repo.speedcubing.top/repository/maven-public-test/
